title: RealityTech projets.
description: List and description of RealityTech open source projects.
show_downloads: false

show_fork: true
lib_name: 
owner_name: Rea-lity-Tech

google-tracking-id: "UA-73807553-1"

lang: "en"
author: "SASU RealityTech"

keywords: "augmented reality, mapping, interactive projection, start-up, france, bordeaux, board games, video games, technology, interactive table, touch surfaces"

# favicon: "/img/favicon-bug.ico"
404-img: "/img/labtocat.png"

black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/bois2.jpg"

# Background credits
# https://www.flickr.com/photos/postneutralicus/30839878074/in/photostream/


email: "laviole@rea.lity.tech"

social:
  - title: "facebook"
    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/rea_lity_tech/"
  - title: "github"
    url: "https://github.com/poqudrof"

404-img: "/img/racoon.jpg"

pages_list:
  Activity: 'activity'
  Contact: 'contact'
  #Timeline: 'timeline'

# Exclusion list from the generated _site

exclude: ["LICENSE", "CONTRIBUTING", "CONTRIBUTORS", "scripts", "ressources", "Gemfile", "Gemfile.lock", "deploy", "build-test", "build-prod"]


# Pagination path
paginate_path: "blog/page:num/"

sass:
  style: compressed

gems:
  - jekyll-paginate

markdown:    kramdown
